// frontend/src/components/Navbar.svelte
<main class="navbar-sticky">
    <nav class="flex justify-between bg-zinc-800 p-5">
        <a href="/" class="hover:text-white text-gray-300 text-xl">ToDo</a>

        <div>
            <a href="/logout" class="hover:text-white text-gray-300 text-lg px-2">Logout</a>
            <a href="/new" class="hover:text-white text-gray-300 text-lg px-2">New Task</a>
        </div>
    </nav>
</main>

// frontend/src/components/NavBar.vue
<template>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="d-flex justify-content-between container-fluid">
            <a href="/" class="navbar-brand text-white px-1">ToDo</a>

            <div class="px-2">
                <a href="/" onclick="localStorage.setItem('token', 'undefined');" class="nav-item text-white text-decoration-none mx-3">Logout</a>
                <a href="/new" class="nav-item text-white text-decoration-none mx-3">New Task</a>
            </div>
        </div>
    </nav>
</template>
